//get all
GET http://localhost:3000/employee


###
//get one
GET http://localhost:3000/employee/674df3a6392b41bb386dd998


###
//create one
POST http://localhost:3000/employee
Content-Type: application/json

{
    "firstName": "person 4",
    "lastName": "person 2 last name",
    "email": "ghgg2h@gmail.com",
    "phoneNumber": "2085456589",
    "jobTitle": "accountant",
    "departmentID": "674d7648e1d23ddf08ef7abc",
    "projectIDs": ["674deffaebc8ce394e6a5495"],
    "managerID": "674df2ba352e8c08199742a9"

}


###
//delete one

DELETE http://localhost:3000/employee/674df66bd223186ab57cff2a


###
// get all departments
GET http://localhost:3000/department


###
//create one department
POST http://localhost:3000/department
Content-Type: application/json

{
    "departmentID": 1,
    "departmentName": "Sales",
    "location": "bariely"

}

###
// get all projects
GET http://localhost:3000/project


###
//create one projects
POST http://localhost:3000/project
Content-Type: application/json

{
    "projectID": 1,
    "projectName": "Sales",
    "endDate": "2025-01-01",
    "budget": 10000

}