//get all
GET http://localhost:3000/employee


###
//get one
GET http://localhost:3000/employee/674d655fafeb2c2902274a8e


###
//create one
POST http://localhost:3000/employee
Content-Type: application/json

{
    "firstName": "person 3",
    "lastName": "person 2 last name",
    "email": "ghgg2h@gmail.com",
    "phoneNumber": "2085456589",
    "jobTitle": "accountant",
    "departmentID": 2,
    "projects": {
        "projectID": 1,
        "projectName": "first project",
        "projectRole": "lead"
    }

}


###
//delete one

DELETE http://localhost:3000/employee/674d726e04f6facfd061d863


###
// get all departments
GET http://localhost:3000/department


###
//create one department
POST http://localhost:3000/department
Content-Type: application/json

{
    "departmentID": 1,
    "departmentName": "Sales",
    "location": "bariely"

}

###
// get all projects
GET http://localhost:3000/project


###
//create one projects
POST http://localhost:3000/projects
Content-Type: application/json

{
    "projectID": 1,
    "projectName": "Sales",
    "endDate": "2025-01-01",
    "budget": 10000

}